name: Docker Action
on:
  release:
    types: [published]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Build and publish image
        uses: philips-software/docker-ci-scripts@v4.5.0
        with:
          dockerfile: "./Dockerfile"
          image-name: "admin"
          tags: "prod"
        env:
          REGISTRY_USERNAME: ${{ secrets.MISO_REGISTRY_USERNAME }}
          REGISTRY_TOKEN: "${{ secrets.MISO_REGISTRY_TOKEN }}"
          REGISTRY_URL: registry.gitlab.com/mirrish/miso
          PUSH_ON_GIT_TAG: true
          DOCKER_BUILD_ARGS: --label ${{ GITHUB.REF_NAME }}
